### ISSUE TITLE
Front-end work for Project LLM-Assisted Application Evaluation 

### ISSUE THREAD

**Issue by 8arry** [StephenZhaoyi/LLM-Course-Check#9]
##  Description
We need to complete multiple tasks to make sure the front-end works smoothly as designed.

##  Tasks
- [ ] Design the wireframe for the project
- [ ] Design User Interface
- [ ] Integrate with backend
- [ ] Testing
